packages:
  - name: latest-installer
    environment: {}
    parameters: {}
    annotations:
      description: Redirects to the latest installer version in DigitalOcean Spaces
      web-export: true
    functions:
      - name: __main__
        main: __main__.py
        runtime: python:default
